# Generated by Django 3.2.7 on 2021-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
