# Generated by Django 3.2.7 on 2021-10-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='day',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='month',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='week',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goaldetails',
            name='daily_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goaldetails',
            name='monthly_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goaldetails',
            name='weekly_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
